---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-tenant-b
spec:
  endpointSelector: {}
  authentication:
    mode: "required"
  ingress:
    - fromEndpoints:
        - matchLabels:
            app: client-tenant-b
            io.kubernetes.pod.namespace: tenant-b
      toPorts:
        - ports:
            - port: "8080"

