---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-ingress-tenant-b
spec:
  endpointSelector: {}
  egress:
    - toEntities:
        - cluster
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
          rules:
            dns:
              - matchPattern: "*"
  ingress:
    - authentication:
        mode: "required"
    - fromEndpoints:
        - matchLabels:
            app: client-tenant-b
            io.kubernetes.pod.namespace: tenant-b
      toPorts:
        - ports:
            - port: "8080"

