apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tenant-b
resources:
  - mtls-negative-test.yaml
  - client.tenant-a.yaml
  - client.tenant-b.yaml
  - client.tenant-c.yaml
  - policies.yaml
  - server.yaml
