---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: no-spire
---
apiVersion: v1
kind: Pod
metadata:
  name: mtls-negative-test
  labels:
    app: client-tenant-b
spec:
  serviceAccountName: no-spire
  containers:
    - name: client
      image: busybox:latest
      command: ["sleep", "infinity"]
  restartPolicy: Always
